/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib;

import java.awt.Image;
import javax.swing.table.DefaultTableModel;
import orm.Baguera;
//import static model.lib_buscar.campos;
//import static model.lib_buscar.datos;

/**
 *
 * @author lenin
 */
public class lib_buscar extends javax.swing.JDialog {

    /**
     * Creates new form lib_buscar
     */
    public static String datos[][];
    public static String campos[];
    DefaultTableModel dtm;
    public String[] datos_dev;
    public String Clase_lib;
    public String Method_lib;
    public String consulta_bus;
    public String[] campos_busqueda;
    private String paginacion;
    private String n_pagina;
    
    public lib_buscar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        //
        java.awt.Dimension dim = getToolkit().getScreenSize();
        java.awt.Rectangle abounds = getBounds();
        setLocation((dim.width - abounds.width) / 2, (dim.height - abounds.height) / 2);
        //
           Image imagen=getToolkit().getImage(getClass().getResource("/img/sumak.jpg"));
        setIconImage(imagen);
        busca_reg.requestFocusInWindow();
        busca_reg.setText("");
    }
    
    public void iniciar() {
        this.n_pagina = "1";
        this.paginacion = "0";
        pag.setText(n_pagina);
        dtm = new DefaultTableModel(datos, campos);
        tabla_master.setModel(dtm);
        //tabla_master.setModel(new DefaultTableModel(datos, campos));
        jScrollPane1.setViewportView(tabla_master);
        select_reg.setModel(new javax.swing.DefaultComboBoxModel(campos));
        select_reg.setSelectedIndex(1);
        busca_reg.setFocusable(true);
        pag.setText(n_pagina);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        busca_reg = new javax.swing.JTextField();
        select_reg = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_master = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        atr = new javax.swing.JButton();
        sig = new javax.swing.JButton();
        pag = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setToolTipText("LISTA");

        jLabel1.setText("Filtar por:");

        jLabel2.setText("Buscar");

        busca_reg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busca_regKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busca_regKeyReleased(evt);
            }
        });

        select_reg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(select_reg, 0, 294, Short.MAX_VALUE)
                    .addComponent(busca_reg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(select_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(busca_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tabla_master.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_master.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_masterMouseClicked(evt);
            }
        });
        tabla_master.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_masterKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabla_masterKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_master);

        atr.setText("< Atras");
        atr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrActionPerformed(evt);
            }
        });

        sig.setText("Siguiente >");
        sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigActionPerformed(evt);
            }
        });

        pag.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pag, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sig)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atr)
                    .addComponent(pag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sig))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_masterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_masterMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        int c = dtm.getColumnCount();
        //int r = dtm.getRowCount();
        int r = this.tabla_master.getSelectedRow();
        //System.out.print(c+""+r);
        datos_dev = new String[c];
        for (int i = 0; i < c; i++) {
            datos_dev[i] = (String) dtm.getValueAt(r, i);
        }
        Datos(datos_dev);
    }//GEN-LAST:event_tabla_masterMouseClicked

    private void busca_regKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busca_regKeyPressed
        // TODO add your handling code here:
//        int i = select_reg.getSelectedIndex();
//        Baguera p = new Baguera();
//        String campos_datos = this.campos_busqueda[i];
//        String consulta = this.consulta_bus + " and " + campos_datos + " like '%" + busca_reg.getText() + "%' order by 1 desc limit 50";
//        datos = p.Execute(consulta);
//        dtm = new DefaultTableModel(datos, campos);
//        tabla_master.setModel(dtm);
    }//GEN-LAST:event_busca_regKeyPressed

    private void busca_regKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busca_regKeyReleased
        // TODO add your handling code here:
        this.n_pagina = "1";
        this.paginacion = "0";
        int i = select_reg.getSelectedIndex();
        Baguera p = new Baguera();
        String campos_datos = this.campos_busqueda[i];
        String consulta = this.consulta_bus + " and " + campos_datos + " like '%" + busca_reg.getText() + "%' order by 1 desc limit 50 offset 0";
        datos = p.Execute(consulta);
        dtm = new DefaultTableModel(datos, campos);
        tabla_master.setModel(dtm);
        pag.setText(n_pagina);
    }//GEN-LAST:event_busca_regKeyReleased

    private void atrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrActionPerformed
        // TODO add your handling code here:
        //this.paginacion = pag.getText();
        if (this.paginacion.equals("")) {
            this.paginacion = "0";
        }
        if (Integer.parseInt(this.paginacion) > 0) {
            this.paginacion = String.valueOf(Integer.parseInt(this.paginacion) - 50);
            this.n_pagina = String.valueOf(Integer.parseInt(n_pagina) - 1);
        }
        int i = select_reg.getSelectedIndex();
        Baguera p = new Baguera();
        String campos_datos = this.campos_busqueda[i];
        String consulta = this.consulta_bus + " and " + campos_datos + " like '%" + busca_reg.getText() + "%' order by 1 desc limit 50 OFFSET " + this.paginacion;
        datos = p.Execute(consulta);
        dtm = new DefaultTableModel(datos, campos);
        tabla_master.setModel(dtm);
        pag.setText(this.n_pagina);
    }//GEN-LAST:event_atrActionPerformed

    private void sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigActionPerformed
        // TODO add your handling code here:
        //  this.paginacion = pag.getText();
        if (this.paginacion.equals("")) {
            this.paginacion = "0";
        }
        this.paginacion = String.valueOf(Integer.parseInt(this.paginacion) + 50);
        this.n_pagina = String.valueOf(Integer.parseInt(n_pagina) + 1);
        int i = select_reg.getSelectedIndex();
        Baguera p = new Baguera();
        String campos_datos = this.campos_busqueda[i];
        String consulta = this.consulta_bus + " and " + campos_datos + " like '%" + busca_reg.getText() + "%' order by 1 desc limit 50 OFFSET " + this.paginacion;
        datos = p.Execute(consulta);
        dtm = new DefaultTableModel(datos, campos);
        tabla_master.setModel(dtm);
        pag.setText(this.n_pagina);
    }//GEN-LAST:event_sigActionPerformed

    private void tabla_masterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_masterKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==evt.VK_ENTER) {
             setVisible(false);
        int c = dtm.getColumnCount();
        //int r = dtm.getRowCount();
        int r = this.tabla_master.getSelectedRow();
        //System.out.print(c+""+r);
        datos_dev = new String[c];
        for (int i = 0; i < c; i++) {
            datos_dev[i] = (String) dtm.getValueAt(r, i);
        }
        Datos(datos_dev);
        }
    }//GEN-LAST:event_tabla_masterKeyPressed

    private void tabla_masterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_masterKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_masterKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(lib_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(lib_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(lib_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(lib_buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                lib_buscar dialog = new lib_buscar(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atr;
    private javax.swing.JTextField busca_reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pag;
    private javax.swing.JComboBox select_reg;
    private javax.swing.JButton sig;
    private javax.swing.JTable tabla_master;
    // End of variables declaration//GEN-END:variables

    public void Datos(String datos[]) {
        Baguera p = new Baguera();
        p.dato_dev = datos;
        p.Clase_lib = this.Clase_lib;
        p.Method_lib = this.Method_lib;
        p.setExecute();
        
    }
}
